### ISSUE TITLE
Absolute paths

### ISSUE THREAD

**Issue by mvasin** [wildlyinaccurate/jekyll-responsive-image#1]
Hello Joseph,

thanks for the plugin! Here's are the issues:

1) I can't make it work with absolute paths. And absolute path are obligatory according to https://yoast.com/dev-blog/relative-urls-issues/
2) I don't like creating temp files in my project /img/ folder and then copying it to production folder. I like the idea of having only source files in the project folder and having temporary/rendered files in _site folder. Or did I just set it wrong?

**Comment by wildlyinaccurate** [comment]
Hello,

1) You can choose to use absolute paths simply by modifying the template. For instance, you can prepend your site's base URL like so:

```liquid
<img src="{{ path  | prepend: site.baseurl | prepend: site.url }}" ...>
```

2) I'm not sure what you mean? The intention of this plugin is that you have source files at the original dimensions (e.g. `assets/*.jpg` or `img/*.jpg`). When you build, those source files are copied to _site, and they are also resized to _site/{dir}/resized.

So, given the following files in your project:

```
| - img
  | - 1.jpg
  | - 2.jpg
```

You should end up with this after a build:

```
| - img
  | - 1.jpg
  | - 2.jpg

| - _site
  | - img
    | - 1.jpg
    | - 2.jpg
    | - resized
      | - 1-320x80.jpg
      | - 2-320x80.jpg
```

**Comment by mvasin** [comment]
Thanks for the answer, Joseph!

1) site.url variable is magically unavailable in _includes/responsive-image.html
`test: {{site.url}}` prints only `test:`, `{{ path | prepend: site.title}}` prepends nothing.

2) I made a clean install of jekyll and just copied and pasted your example code for `_includes/responsive-image.html` and `_config.yml`, and even created `assets/my-file.jpg`.

And... the plugin created `resized` folder both in jekyll's root `assets` folder and `_site/assets` folder. So at least your example configuration behaves not according to your intentions. Please check it yourself.

**Comment by hasselg** [comment]
Hi @wildlyinaccurate, I'm seeing something similar to the second point brought up here.

After building only once, none of the resized images are being moved into my `_site` folder, residing in only my assets folder. I have to build a second time to get them moved over.

Pre-build:
```
| - _config.yml
| - assets
  | - 1.jpg
| - _ site
```
After the first build:
```
| - _config.yml
| - assets
  | - 1.jpg
  | - resized
    | - 1-320-80.jpg
| - _site
  | - assets
    | - 1.jpg
```

I have to build a second time to get the resized images copied over into my `_site`.
After the second build:
```
| - _config.yml
| - assets
  | - 1.jpg
  | - resized
    | - 1-320-80.jpg
| - _site
  | - assets
    | - 1.jpg
    | - resized
      | - 1-320-80.jpg
```

**Comment by wildlyinaccurate** [comment]
@hasselg thanks, I think I understand now. Probably what's happening is the resized assets are built _after_ the `_site/` copy happens. I'll look into this ASAP.

**Comment by hasselg** [comment]
@wildlyinaccurate thank you very much for starting the investigation. I recently started using your plugin and am liking it very much!

**Comment by wildlyinaccurate** [comment]
I've fixed that issue in #2 (released as version 0.12.0 of the Gem) and tested it on a couple of sites -- both of which now have the resized images in _site on the first build.

@mvasin, next on my list is that absolute path issue. the `site` variable *should* be available in the image template but I think I know why it *isn't*. Hopefully I can fix that soon.

**Comment by wildlyinaccurate** [comment]
Version 0.13.0 of the Gem includes #3, which should allow you to use `site` (and `jekyll`) variables in the templates. Hopefully that solves your absolute paths issue!

**Comment by hasselg** [comment]
Hi @wildlyinaccurate,

I'm still seeing an issue. I've updated to the latest gem 0.13.0 and what I'm seeing is the correct folder get created in the _site folder but without its contents. Again, if I run jekyll build twice, things are as I would expect. Does that sound like I'm just messing something up?

hassle

**Comment by wildlyinaccurate** [comment]
Hmm, that's odd. I had tested it with a couple of different Jekyll sites but I'll try again with a totally fresh Jekyll install. If it's not a pain, would you mind pasting your Jekyll configuration here? Just in case I'm missing some edge case.

**Comment by hasselg** [comment]
Here is my site config:
```
timezone: America/New_York

# Site settings
title: 'GHB'
tagline: Blarrgg
email: ghasseler@gmail.com
sidebar_image: /images/bg-moose.jpeg

twitter_username:     hasselg
github_username:      hasselg
linkedin_username:    gregoryhasseler     

# Build settings
baseurl:   /
url: http://www.gregoryhasseler.com
markdown: redcarpet
highlighter: pygments

responsive_image:
  template: _includes/responsive-image.html
  output_path_format: assets/photos/resized/%{width}/%{basename}
  sizes:
    - width: 120
    - width: 320
    - width: 640
    - width: 960

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag-archive-layout
  permalinks:
    tag: '/tag/:name/'

gems:
  - jekyll-archives
  - jekyll-sitemap
```

Do I maybe need to make an adjustment to the output_path_format to reflect the _site destination?
